---
- name: CREATE VRF
  hosts: "{{ apic }}"
  gather_facts: False

  vars:
    tenant_name: Bank_Test
    vrf_name: Development

  tasks:

    - name: Create VRF
      aci_vrf:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        tenant: "{{ tenant_name }}"
        vrf: "{{ vrf_name }}"
        description: Development VRF
        state: present
      delegate_to: localhost
