---
- name: CREATE CONTRACT AND SUBJECTS
  hosts: "{{ apic }}"
  gather_facts: False

  vars:
    tenant_name: Bank_Test
    contract_web:
      name: Web_Contract
      subject: Web_Subject
      filter: Web_Filter

  tasks:

    - name: Create Contract
      aci_contract:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        tenant: "{{ tenant_name }}"
        contract: "{{ contract_web.name }}"
        description: Contract Services HTTP
        state: present
      delegate_to: localhost

    - name: Create Subject
      aci_contract_subject:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        tenant: "{{ tenant_name }}"
        contract: "{{ contract_web.name }}"
        subject: "{{ contract_web.subject }}"
        description: Subject HTTP
        state: present
      delegate_to: localhost

    - name: Add Filter to Subject
      aci_contract_subject_to_filter:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        tenant: "{{ tenant_name }}"
        contract: "{{ contract_web.name }}"
        subject: "{{ contract_web.subject }}"
        filter: "{{ contract_web.filter }}"
        state: present
      delegate_to: localhost
