---
- name: CREATE BD
  hosts: "{{ apic }}"
  gather_facts: False

  vars:
    tenant_name: Bank_Test
    vrf_name: Development
    bd_name: BD_VLAN_10
    subnet: 192.168.10.1/24

  tasks:

    - name: Create BD
      aci_bd:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        tenant: "{{ tenant_name }}"
        vrf: "{{ vrf_name }}"
        bd: "{{ bd_name }}"
        description: Vlan 10 BD
        state: present      
      delegate_to: localhost

    - name: Asign Subnet
      aci_bd_subnet:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        tenant: "{{ tenant_name }}"
        bd: "{{ bd_name }}"
        gateway: "{{ subnet.split('/') | first }}"
        mask: "{{ subnet.split('/') | last }}"
        description: Vlan 10 Subnet
        state: present      
      delegate_to: localhost
