---
- name: CREATE TENANTS
  hosts: "{{ host }}"
  connection: local
  gather_facts: False

  vars:
    tenant_list:
      - Customer1
      - Customer2

  tasks:

    - name: Create Tenant
      aci_tenant:
        host: "{{ host }}"
        user: "{{ username }}"
        password: "{{ apic_pass }}"
        validate_certs: False

        tenant: "{{ item }}"
        state: present
        description: "Tenant"

      delegate_to: localhost
      loop: "{{ tenant_list }}"