---
- name: CREATE TENANT
  hosts: "{{ host }}"
  connection: local
  gather_facts: False

  tasks:

    - name: Create Tenant
      aci_tenant:
        host: "{{ host }}"
        user: "{{ username }}"
        password: "{{ apic_pass }}"
        validate_certs: False

        tenant: "Support"
        description: "The Support Organization"
        state: present

      delegate_to: localhost