---
- name: CREATE TENANTS
  hosts: "{{ apic }}"
  connection: local
  gather_facts: False

  vars:
    tenant_list:
      - Bank_Test
      - Bank_Prod

  tasks:

    - name: Create Tenant
      aci_tenant:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        tenant: "{{ item }}"
        state: present
        description: "Tenant"
      delegate_to: localhost
      loop: "{{ tenant_list }}"