---
- name: CREATE TENANT
  hosts: "{{ host }}"

  tasks:

    - name: Create Tenant
      aci_tenant:
        host: "{{ host }}"
        user: "{{ username }}"
        password: "{{ apic_pass }}"
        validate_certs: "{{ validate_certs }}"

        tenant: "Support"
        description: "The Support Organization"
        state: present

      delegate_to: localhost