---
- name: DELETE TENANTS
  hosts: "{{ apic }}"
  gather_facts: False

  vars:
    tenant_name: Bank_Test

  tasks:

    - name: Delete Tenant
      aci_tenant:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        tenant: "{{ tenant_name }}"
        state: absent
      
      delegate_to: localhost
