---
---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: 192.168.2.11
  connection: local
  gather_facts: False

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        state: "present"
        validate_certs: False
        tenant: "Banco"
        description: "Tenant Created Using Ansible"