---
- name: QUERY FABRIC AND BUILD REPORT
  hosts: "{{ apic }}"
  connection: local
  gather_facts: False

  tasks:

    - name: Get System Health
      aci_rest:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        path: /api/mo/topology/health.json
        method: get

      delegate_to: localhost
      register: health_system

    - name: PRINT System Health response
      debug:
        var: health_system
    
    - name: PRINT Template health_report_v1
      debug:
        msg: "{{ lookup('template', 'health_report_v1.j2') }}"