---
- name: CREATE TENANTS - REST
  hosts: "{{ apic }}"
  connection: local
  gather_facts: False

  tasks:

    - name: Create Tenant REST
      aci_rest:
        host: "{{ apic }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False

        path: /api/mo/topology/health.json
        method: get
        
      delegate_to: localhost
      register: health_system

    - name: PRINT System Health response
      debug:
        var: health_system
        verbosity: 1